name = "email-send"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-06-14"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
